import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import './UserReports.css';

const UserReports = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('donations');
  const [loading, setLoading] = useState(true);
  
  const [donations, setDonations] = useState([]);
  const [rescueReports, setRescueReports] = useState([]);
  const [sponsorships, setSponsorships] = useState([]);
  const [volunteerApps, setVolunteerApps] = useState([]);
  
  const [summary, setSummary] = useState({
    totalDonated: 0,
    totalReports: 0,
    totalSponsorships: 0,
    childrenRescued: 0
  });

  useEffect(() => {
    fetchAllData();
  }, []);

  const fetchAllData = async () => {
    setLoading(true);
    try {
      const userEmail = localStorage.getItem('userEmail');
      const userName = localStorage.getItem('userName');
      
      const storedDonations = JSON.parse(localStorage.getItem('userDonations') || '[]');
      const userDonations = storedDonations.filter(d => d.donorEmail === userEmail || d.donorName === userName);
      setDonations(userDonations);
      
      const storedReports = JSON.parse(localStorage.getItem('orphanReports') || '[]');
      const userReports = storedReports.filter(r => r.reportedBy === userName || r.contactPerson === userName);
      setRescueReports(userReports);
      
      try {
        const response = await fetch(`http://localhost:5000/api/sponsorships/my-sponsorships?email=${userEmail}`);
        const data = await response.json();
        if (data.success) {
          setSponsorships(data.sponsorships || []);
        }
      } catch (error) {
        console.error('Error fetching sponsorships:', error);
      }
      
      try {
        const response = await fetch(`http://localhost:5000/api/volunteer/my-applications?name=${userName}`);
        const data = await response.json();
        if (data.success) {
          setVolunteerApps(data.applications || []);
        }
      } catch (error) {
        console.error('Error fetching volunteer apps:', error);
      }
      
      const totalDonated = userDonations.reduce((sum, d) => sum + (d.amountValue || 0), 0);
      const resolvedReports = userReports.filter(r => r.rescueStatus === 'resolved').length;
      
      setSummary({
        totalDonated: totalDonated,
        totalReports: userReports.length,
        totalSponsorships: sponsorships.length,
        childrenRescued: resolvedReports
      });
      
    } catch (error) {
      console.error('Error fetching data:', error);
    } finally {
      setLoading(false);
    }
  };

  const exportToPDF = (data, title, columns) => {
    if (!data || data.length === 0) {
      alert('No data to export');
      return;
    }

    const doc = new jsPDF();
    const userName = localStorage.getItem('userName') || 'User';
    const currentDate = new Date().toLocaleString();

    doc.setFillColor(44, 122, 77);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 20, 25);
    
    doc.setFontSize(10);
    doc.setTextColor(200, 200, 200);
    doc.text(`Generated by: ${userName}`, 20, 35);
    doc.text(`Date: ${currentDate}`, 150, 35, 'right');
    
    doc.setFontSize(14);
    doc.setTextColor(44, 122, 77);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary', 20, 55);
    
    doc.setDrawColor(44, 122, 77);
    doc.line(20, 60, 190, 60);
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Donations Rs: ${summary.totalDonated.toLocaleString()}`, 20, 70);
    doc.text(`Total Reports: ${summary.totalReports}`, 20, 78);
    doc.text(`Total Sponsorships: ${summary.totalSponsorships}`, 20, 86);
    doc.text(`Children Rescued: ${summary.childrenRescued}`, 20, 94);
    
    const tableData = data.map(row => {
      return columns.map(col => {
        let value = row[col.key];
        if (col.key === 'date' || col.key === 'createdAt' || col.key === 'joinedAt' || col.key === 'reportedAt') {
          value = new Date(value).toLocaleDateString();
        }
        if (col.key === 'amount' || col.key === 'amountValue') {
          value = `₹${value}`;
        }
        if (col.key === 'skills' && Array.isArray(value)) {
          value = value.join(', ');
        }
        return value || '-';
      });
    });
    
    const tableColumns = columns.map(col => col.label);
    
    autoTable(doc, {
      startY: 105,
      head: [tableColumns],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: [44, 122, 77],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252]
      },
      styles: {
        fontSize: 9,
        cellPadding: 3
      },
      margin: { left: 20, right: 20 }
    });
    
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`NurtureOrphan - Page ${i} of ${pageCount}`, 105, 285, 'center');
    }
    
    doc.save(`${title.toLowerCase().replace(/ /g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const handleExportDonations = () => {
    const columns = [
      { key: 'date', label: 'Date' },
      { key: 'amountValue', label: 'Amount' },
      { key: 'type', label: 'Type' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'transactionId', label: 'Transaction ID' },
      { key: 'status', label: 'Status' }
    ];
    exportToPDF(donations, 'My Donations Report', columns);
  };

  const handleExportRescues = () => {
    const columns = [
      { key: 'reportedAt', label: 'Date' },
      { key: 'childName', label: 'Child Name' },
      { key: 'location', label: 'Location' },
      { key: 'city', label: 'City' },
      { key: 'childAge', label: 'Age' },
      { key: 'rescueStatus', label: 'Status' }
    ];
    exportToPDF(rescueReports, 'My Rescue Reports', columns);
  };

  const handleExportSponsorships = () => {
    const columns = [
      { key: 'createdAt', label: 'Date' },
      { key: 'orphanageName', label: 'Orphanage' },
      { key: 'amount', label: 'Amount' },
      { key: 'sponsorshipType', label: 'Type' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'status', label: 'Status' }
    ];
    exportToPDF(sponsorships, 'My Sponsorships Report', columns);
  };

  const handleExportVolunteer = () => {
    const columns = [
      { key: 'joinedAt', label: 'Date' },
      { key: 'skills', label: 'Skills' },
      { key: 'availability', label: 'Availability' },
      { key: 'city', label: 'City' },
      { key: 'status', label: 'Status' }
    ];
    exportToPDF(volunteerApps, 'My Volunteer Applications', columns);
  };

  const getStatusBadge = (status) => {
    switch(status) {
      case 'completed': 
        return <span className="badge completed">✓ Completed</span>;
      case 'pending': 
        return <span className="badge pending">⏳ Pending</span>;
      case 'resolved': 
        return <span className="badge resolved">✓ Resolved</span>;
      case 'active': 
        return <span className="badge active">✅ Active</span>;
      default: 
        return <span className="badge pending">{status}</span>;
    }
  };

  if (loading) {
    return (
      <div className="user-reports-container">
        <div className="loading-state">
          <i className="fas fa-spinner fa-spin"></i>
          <p>Loading your reports...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="user-reports-container">
      <button className="back-btn" onClick={() => navigate(-1)}>
        <i className="fas fa-arrow-left"></i> Back to Dashboard
      </button>
        <h1><i className="fas fa-chart-line"></i> My Activity Reports</h1>

      <div className="reports-header">
        <p>View all your contributions and activities</p>
      </div>

      <div className="summary-cards">
        <div className="summary-card">
          <div className="card-icon"><i className="fas fa-rupee-sign"></i></div>
          <div className="card-info">
            <h3>₹{summary.totalDonated.toLocaleString()}</h3>
            <p>Total Donated</p>
          </div>
        </div>
        <div className="summary-card">
          <div className="card-icon"><i className="fas fa-ambulance"></i></div>
          <div className="card-info">
            <h3>{summary.totalReports}</h3>
            <p>Rescue Reports</p>
          </div>
        </div>
        <div className="summary-card">
          <div className="card-icon"><i className="fas fa-hand-holding-heart"></i></div>
          <div className="card-info">
            <h3>{summary.totalSponsorships}</h3>
            <p>Sponsorships</p>
          </div>
        </div>
        <div className="summary-card">
          <div className="card-icon"><i className="fas fa-child"></i></div>
          <div className="card-info">
            <h3>{summary.childrenRescued}</h3>
            <p>Children Rescued</p>
          </div>
        </div>
      </div>

      <div className="reports-tabs">
        <button className={`tab ${activeTab === 'donations' ? 'active' : ''}`} onClick={() => setActiveTab('donations')}>
          <i className="fas fa-hand-holding-usd"></i> Donations
        </button>
        <button className={`tab ${activeTab === 'rescues' ? 'active' : ''}`} onClick={() => setActiveTab('rescues')}>
          <i className="fas fa-ambulance"></i> Rescue Reports
        </button>
        <button className={`tab ${activeTab === 'sponsorships' ? 'active' : ''}`} onClick={() => setActiveTab('sponsorships')}>
          <i className="fas fa-hand-holding-heart"></i> Sponsorships
        </button>
        <button className={`tab ${activeTab === 'volunteer' ? 'active' : ''}`} onClick={() => setActiveTab('volunteer')}>
          <i className="fas fa-hands-helping"></i> Volunteer
        </button>
      </div>

      <div className="export-section">
        {activeTab === 'donations' && donations.length > 0 && (
          <button className="export-btn pdf" onClick={handleExportDonations}>
            <i className="fas fa-file-pdf"></i> Export to PDF
          </button>
        )}
        {activeTab === 'rescues' && rescueReports.length > 0 && (
          <button className="export-btn pdf" onClick={handleExportRescues}>
            <i className="fas fa-file-pdf"></i> Export to PDF
          </button>
        )}
        {activeTab === 'sponsorships' && sponsorships.length > 0 && (
          <button className="export-btn pdf" onClick={handleExportSponsorships}>
            <i className="fas fa-file-pdf"></i> Export to PDF
          </button>
        )}
        {activeTab === 'volunteer' && volunteerApps.length > 0 && (
          <button className="export-btn pdf" onClick={handleExportVolunteer}>
            <i className="fas fa-file-pdf"></i> Export to PDF
          </button>
        )}
      </div>

      {activeTab === 'donations' && (
        <div className="data-table-container">
          {donations.length === 0 ? (
            <div className="empty-state">
              <i className="fas fa-gift"></i>
              <h3>No Donations Yet</h3>
              <p>Your first donation will appear here</p>
              <button className="action-btn" onClick={() => navigate('/donation')}>Make a Donation</button>
            </div>
          ) : (
            <table className="data-table">
              <thead>
                <tr>
                  <th>Date</th><th>Amount</th><th>Type</th><th>Purpose</th><th>Transaction ID</th><th>Status</th>
                </tr>
              </thead>
              <tbody>
                {donations.map((donation, index) => (
                  <tr key={index}>
                    <td>{new Date(donation.date).toLocaleDateString()}</td>
                    <td className="amount">₹{donation.amountValue}</td>
                    <td>{donation.type === 'monthly' ? 'Monthly' : 'One Time'}</td>
                    <td>{donation.purpose || 'General'}</td>
                    <td className="txn-id">{donation.transactionId || donation.id}</td>
                    <td>{getStatusBadge(donation.status || 'completed')}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {activeTab === 'rescues' && (
        <div className="data-table-container">
          {rescueReports.length === 0 ? (
            <div className="empty-state">
              <i className="fas fa-file-alt"></i>
              <h3>No Rescue Reports</h3>
              <p>When you report an orphan, it will appear here</p>
              <button className="action-btn" onClick={() => navigate('/report-orphan')}>Report an Orphan</button>
            </div>
          ) : (
            <table className="data-table">
              <thead>
                <tr>
                  <th>Date</th><th>Child Name</th><th>Location</th><th>City</th><th>Age</th><th>Status</th>
                </tr>
              </thead>
              <tbody>
                {rescueReports.map((report, index) => (
                  <tr key={index}>
                    <td>{new Date(report.reportedAt).toLocaleDateString()}</td>
                    <td>{report.childName || 'Unknown'}</td>
                    <td>{report.location}</td>
                    <td>{report.city}</td>
                    <td>{report.childAge} years</td>
                    <td>{getStatusBadge(report.rescueStatus)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {activeTab === 'sponsorships' && (
        <div className="data-table-container">
          {sponsorships.length === 0 ? (
            <div className="empty-state">
              <i className="fas fa-hand-holding-heart"></i>
              <h3>No Sponsorships</h3>
              <p>Sponsor an orphanage to see your contributions here</p>
              <button className="action-btn" onClick={() => navigate('/sponsorships')}>Sponsor Now</button>
            </div>
          ) : (
            <table className="data-table">
              <thead>
                <tr>
                  <th>Date</th><th>Orphanage</th><th>Amount</th><th>Type</th><th>Purpose</th><th>Status</th>
                </tr>
              </thead>
              <tbody>
                {sponsorships.map((sponsorship, index) => (
                  <tr key={index}>
                    <td>{new Date(sponsorship.createdAt).toLocaleDateString()}</td>
                    <td>{sponsorship.orphanageName}</td>
                    <td className="amount">${sponsorship.amount}</td>
                    <td>{sponsorship.sponsorshipType}</td>
                    <td>{sponsorship.purpose}</td>
                    <td>{getStatusBadge(sponsorship.status)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {activeTab === 'volunteer' && (
        <div className="data-table-container">
          {volunteerApps.length === 0 ? (
            <div className="empty-state">
              <i className="fas fa-hands-helping"></i>
              <h3>No Volunteer Applications</h3>
              <p>Apply as a volunteer to see your applications here</p>
              <button className="action-btn" onClick={() => navigate('/volunteer-apply')}>Apply Now</button>
            </div>
          ) : (
            <table className="data-table">
              <thead>
                <tr>
                  <th>Date</th><th>Skills</th><th>Availability</th><th>City</th><th>Status</th>
                </tr>
              </thead>
              <tbody>
                {volunteerApps.map((app, index) => (
                  <tr key={index}>
                    <td>{new Date(app.joinedAt).toLocaleDateString()}</td>
                    <td>{app.skills?.slice(0, 3).join(', ') || 'General'}</td>
                    <td>{app.availability}</td>
                    <td>{app.city}</td>
                    <td>{getStatusBadge(app.status)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}
    </div>
  );
};

export default UserReports;